#!/usr/local/bin/bash

#    _____  _____
#   |  __ \|  __ \    AUTHOR: Pedro Rivero
#   | |__) | |__) |   ---------------------------------
#   |  ___/|  _  /    DATE: November 16, 2019
#   | |    | | \ \    ---------------------------------
#   |_|    |_|  \_\   https://github.com/pedrorrivero
#

# ---------------------------------------- #
#                 INSTALL                  #
# ---------------------------------------- #

if [ ! -e "uninstall" ]; then
  echo "ERROR: Missing file './uninstall'." >&2
  echo "Please run this installation from within its parent directory: './install'." >&2
  exit 1
else
  chmod 766 'uninstall'
  source 'uninstall' &>/dev/null
fi

if [ ! -e "${BIN_NAME}.${BIN_EXTENSION}" ]; then
  echo "ERROR: Missing file '${BIN_NAME}.${BIN_EXTENSION}'." >&2
  echo "Please run this installation from within its parent directory: './install'." >&2

else

  chmod 766 "${BIN_NAME}.${BIN_EXTENSION}"

  ln -s "${PWD}/${BIN_NAME}.${BIN_EXTENSION}" "${BIN_PATH}"

  echo "Succesful installation of ${BIN_NAME}!"

fi
